201124 web api backend
Code2Gether-Discord/Code2Gether-Discord-Bot pull request #32
Opened 2020-11-30 15:08 UTC by DonSagiv

2020-12-04 16:25 UTC, nickmartin1ee7 commented
@DonSagiv please resolve merge conflicts

2020-12-04 17:01 UTC, nickmartin1ee7 requested changes
Some of the tests are broken by these changes. The project repositories need to be updated to handle the interact between the API and logic.
The ProjectDAL class will be here requests are made to the API endpoints.
The FakeProjectRepository will usually be a couple dictionaries of in memory tables that mimic the database.
The ProjectManager will be in charge of handling interactions with the IProjectRepository within logic.

2020-12-04 17:01 UTC, nickmartin1ee7 commented on Code2Gether-Discord-Bot.Library/BusinessLogic/ListProjectsLogic.cs
> +                /*
Why is this commented out?

2020-12-04 17:01 UTC, nickmartin1ee7 commented on Code2Gether-Discord-Bot.Library/BusinessLogic/JoinProjectLogic.cs
> +            /*
Why is this commented out?

2020-12-04 17:01 UTC, nickmartin1ee7 commented on Code2Gether-Discord-Bot.Library/BusinessLogic/JoinProjectLogic.cs
> +            // todo: Load user or create new one.
TODO present in changes

2020-12-04 17:01 UTC, nickmartin1ee7 commented on Code2Gether-Discord-Bot.Library/Models/Project.cs
> -        public bool IsActive
I assume this will be implemented somewhere else?

2020-12-04 17:01 UTC, nickmartin1ee7 commented on Code2Gether-Discord-Bot.Library/Models/ProjectManager.cs
> +            if (project.ProjectMembers.Contains(user)) return false; // User may not already be in project
This should make a call to the ProjectDAL adding the user to a project

2020-12-04 17:01 UTC, nickmartin1ee7 commented on Code2Gether-Discord-Bot.Library/Models/ProjectMember.cs
> +        [ForeignKey(nameof(Member))]
It seems no Primary Key is specified here. I'm not sure how EF implements composite tables but technically, `PROJECT_ID` and `MEMBER_ID` are both PKs & FKs.

2020-12-04 17:01 UTC, nickmartin1ee7 commented on Code2Gether-Discord-Bot.Tests/JoinProjectTests.cs
> +            // Assert.IsTrue(_repo.Read(0).ProjectMembers.Count > 0);
Test method missing an assertion. This should be checking the ProjectMember table via the FakeProjectRepository

2020-12-04 17:01 UTC, nickmartin1ee7 commented on Code2Gether-Discord-Bot.Tests/Fakes/FakeProjectManager.cs
>  ﻿using System;
This class can be deleted, since it should not be faked. Only the repository is.

2020-12-04 17:01 UTC, nickmartin1ee7 commented on Code2Gether-Discord-Bot.WebApi/Controllers/MembersController.cs
> +            _dbContext.Members.Remove(memberToRemove);
Is there no upsert or update method? Do we have to rely on deleting & adding?

2020-12-04 17:01 UTC, nickmartin1ee7 commented on Code2Gether-Discord-Bot.WebApi/Controllers/ProjectMemberController.cs
> +                return NotFound("Umable to find project member.");
Typo: "Umable" -> "Unable"

2020-12-04 17:01 UTC, nickmartin1ee7 commented on Code2Gether-Discord-Bot.WebApi/Controllers/ProjectsController.cs
> +            await _dbContext.Projects.AddAsync(projectToUpdate);
See related comment regarding upsert/insert.

2020-12-04 17:01 UTC, nickmartin1ee7 commented on Code2Gether-Discord-Bot.WebApi/DbContexts/DiscordBotDbContext.cs
> +            modelBuilder.Entity<ProjectMember>(b => b.HasKey(x => new { x.MemberID, x.ProjectID }));
Ah, this must be where the PKs are set for the composite table

2020-12-04 17:01 UTC, nickmartin1ee7 commented on Code2Gether-Discord-Bot.WebApi/Migrations/20201130025543_InitialCreate.Designer.cs
> +                    b.HasIndex("ProjectID");
Is this missing the link to `MemberID`?

2020-12-04 17:01 UTC, nickmartin1ee7 commented on Code2Gether-Discord-Bot.WebApi/Migrations/20201130025543_InitialCreate.cs
> +                    PROJECT_NAME = table.Column<string>(type: "TEXT", nullable: true),
Project Name should not be nullable

2020-12-04 17:01 UTC, nickmartin1ee7 commented on Code2Gether-Discord-Bot.WebApi/Migrations/DiscordBotDbContextModelSnapshot.cs
> +                    b.HasIndex("ProjectID");
See previous comment regarding link to MemberID

2020-12-04 17:01 UTC, nickmartin1ee7 commented on Code2Gether-Discord-Bot.Library/BusinessLogic/CreateProjectLogic.cs
> +                // todo: Load user or create new one.
TODO present in changes

2020-12-04 17:54 UTC, DonSagiv commented on Code2Gether-Discord-Bot.Library/BusinessLogic/ListProjectsLogic.cs
> +                /*
The "Project" model no longer has a "Members" property. This will need to be refactored to consider the new "ProjectMember" model.

2020-12-04 17:55 UTC, DonSagiv commented on Code2Gether-Discord-Bot.Library/Models/ProjectManager.cs
> +            if (project.ProjectMembers.Contains(user)) return false; // User may not already be in project
Like the previous "comment out" -- Projects no longer has a "Members" property. It needs to be re-factored.

2020-12-04 17:57 UTC, DonSagiv commented on Code2Gether-Discord-Bot.Library/Models/Project.cs
> -        public bool IsActive
Probably. We would query the ProjectMembers table to see if it's active or not. We can consider making a view for this data.

2020-12-04 17:59 UTC, DonSagiv commented on Code2Gether-Discord-Bot.Library/Models/ProjectMember.cs
> +        [ForeignKey(nameof(Member))]
In EF, you can't use attributes to define multiple primary keys, so it had to be defined in the DBContext. Refer to [DiscordBotDbContext](https://github.com/Code2Gether-Discord/Code2Gether-Discord-Bot/blob/201124_WebApi_Backend/Code2Gether-Discord-Bot.WebApi/DbContexts/DiscordBotDbContext.cs) in the "OnModelCreating" method, line 29.

2020-12-04 18:00 UTC, DonSagiv commented on Code2Gether-Discord-Bot.Tests/JoinProjectTests.cs
> +            // Assert.IsTrue(_repo.Read(0).ProjectMembers.Count > 0);
Right, except the Project group no longer has a `ProjectMembers` property. We will have to refactor.

2020-12-04 18:01 UTC, DonSagiv commented on Code2Gether-Discord-Bot.WebApi/DbContexts/DiscordBotDbContext.cs
> +            modelBuilder.Entity<ProjectMember>(b => b.HasKey(x => new { x.MemberID, x.ProjectID }));
Yep 😄

2020-12-04 18:03 UTC, DonSagiv commented on Code2Gether-Discord-Bot.WebApi/Migrations/20201130025543_InitialCreate.cs
> +                    PROJECT_NAME = table.Column<string>(type: "TEXT", nullable: true),
Understood. Will fix.

2020-12-04 18:06 UTC, nickmartin1ee7 commented on Code2Gether-Discord-Bot.Library/Models/ProjectManager.cs
> +            if (project.ProjectMembers.Contains(user)) return false; // User may not already be in project
This will need to be replaced by a get method in the DAL and logic implemented here.

2020-12-04 18:07 UTC, nickmartin1ee7 commented on Code2Gether-Discord-Bot.Tests/JoinProjectTests.cs
> +            // Assert.IsTrue(_repo.Read(0).ProjectMembers.Count > 0);
Okay, then the Repository model will have to be refactored to handle CRUD for the 3 tables.

2020-12-06 18:11 UTC, nickmartin1ee7 commented
Converting to a draft until feature is ready to be reviewed and merged

2021-01-05 20:10 UTC, nickmartin1ee7 approved these changes
LGTM

2021-01-05 20:10 UTC, merged